#!/usr/bin/env python3

"""
Converter of VCF (v4.2; generated by GATK) to geno input for rrBLUP (v4.3)  


FEB25th 2016 Junesk9
"""


import sys
import time


vcf = sys.argv[-1]
prefix = ".".join(vcf.split(".")[:-1])+".BLUP.geno"
out = open(prefix,"w")
ctime = time.time()

vcf = [i.strip().split("\t") for i in open(vcf)]
x,y = 0,0
for i in vcf:
	if i[0].startswith("##"):
		pass
	elif i[0].startswith("#C"):
		header = ["marker","chrom","pos"]+i[9:]
		print(*header,sep="\t",file=out)
		h_len = len(header)
	else:
		mark = i[2]
		ch = i[0]
		pos = i[1]
		geno = [mark,ch,pos]
		for snp in i[9:]:
			snp = snp.split(":")[0].split("/")
			try:
				snp = int(snp[0])+int(snp[1])
			except ValueError :
				if snp[0] == ".":
					snp = "NA"
				else: 
					print("error, unexpected genotype %s" % "-".join(geno[:3]+snp))
			if snp == 0:
				geno.append("1")
			elif snp == 1:
				geno.append("0")
			elif snp == 2:
				geno.append("-1")
			elif snp == "NA":
				geno.append("NA")
			else:
				print("unexpected genotype: %s" % "-".join(geno[:3]+[snp]))
				sys.exit(2)
		if len(geno) == h_len:
			print(*geno,sep="\t",file=out)
		else:
			print("error, genotype length not matched to header: %s" % "-".join(geno[:3]))
			sys.exit()
		x += 1
	if x > 99999:
		y += 100000
		ttime = int(time.time() - ctime)
		print("%s lines processed; takes %s sec" % (y,ttime))
		x = 0	
out.close()
		
